FROM eclipse-temurin:17
LABEL mentainer="ronakpanchal1998@gmail.com"
WORKDIR /app
COPY target/springbootdemo-docker-0.0.1-SNAPSHOT.jar /app/springbootdemo-docker-demo.jar
ENTRYPOINT ["java", "-jar", "springbootdemo-docker-demo.jar"]